import struct


ITEM_L_STATUS = (
('active(InStock)', 1),
('active(OutOfStock)', 127),
('customized', 2),
('discontinued', 3),
('display/sample', 4),
('inactive', 5),
('internal use', 6),
('obsolete', 7),
('special order', 8),
)

ITEM_D_STATUS = dict(ITEM_L_STATUS)
ITEM_D_STATUS['active'] = 1

ITEM_L_DEPT = (
('acrylic display cases', 'bakery supplies'),
('adapter plates', 'food storage'),
('air curtain merchandisers', 'refrigeration equipment'),
('air sanitizers and fresheners', 'cleaning supplies'),
('all purpose cleaners', 'cleaners'),
('aluminum foil food wraps', 'd -food prep & wraps'),
('anti fatigue floor mats', 'floor mats'),
('appetizer and tasting dishes', 'dinnerware - serving and display ware'),
('aprons', 'apparel & textile'),
('ashtrays', 'trash containers & receptacles'),
('asian consumables', 'consumables'),
('asian cookware acc.', 'asian cookware'),
('asian cutleries', 'kitchen cutlery'),
('asian pots & pans', 'asian cookware'),
('asianware acc.', 'asianware'),
('assembly fee', 'fees'),
('back bar coolers', 'refrigeration equipment'),
('bain marie pots', 'kitchen supplies'),
('bakery boxes', 'd -food prep & wraps'),
('baking & pastry mats', 'bakery supplies'),
('baking & roast pans', 'bakery supplies'),
('baking cups & molds', 'd -food prep & wraps'),
('baking scrapers & spatulas', 'bakery supplies'),
('ballers', 'bar supplies'),
('banners', 'signs & crowd control'),
('bar condiment dispensers', 'bar supplies'),
('bar mats', 'bar supplies'),
('bar scoops & holders', 'bar supplies'),
('bar stools', 'seating'),
('bar towels', 'bar supplies'),
('basters', 'kitchen supplies'),
('basting spoons', 'serving utensil'),
('batter dispensers', 'kitchen supplies'),
('beer dispensers', 'refrigeration equipment'),
('beer glasses', 'beverageware - glass'),
('bento boxes', 'd -take out containers'),
('beverage dispensers', 'catering supplies'),
('beverage equipment a&p', 'beverage equipments'),
('beverage servers', 'beverageware'),
('beverage signs & labels', 'coffee service'),
('beverage tubs', 'bar supplies'),
('bleach', 'cleaners'),
('blenders', 'food prep equipment'),
('boning & fillet knives', 'kitchen cutlery'),
('booths', 'seating'),
('bottle coolers', 'refrigeration equipment'),
('bottle holders & displays', 'bar supplies'),
('bottle openers & catchers', 'bar supplies'),
('bottles & dispensers', 'asianware'),
('bowls', 'dinnerware - others'),
('braziers', 'cookware'),
('bread & sandwich knives', 'kitchen cutlery'),
('brooms, sweepers & dustpans', 'cleaning supplies'),
('brush mops', 'kitchen utensils'),
('bun & sheet pans', 'bakery supplies'),
('bus boxes', 'bussing & warewashing'),
('bussing carts', 'racks & carts'),
('butcher knives', 'kitchen cutlery'),
('cake pans', 'bakery supplies'),
('call bells', 'kitchen supplies'),
('can openers', 'kitchen supplies'),
('candle, tealight & holders', 'tabletop display & decor'),
('carafes & decanters', 'beverageware'),
('cash registers', 'office supplies'),
('cast iron fry pans', 'cookware'),
('catalina mats', 'floor mats'),
('chafer a&p', 'catering supplies'),
('chafers, chafer pots & woks', 'catering supplies'),
('chafing dish & cooking fuels', 'catering supplies'),
('chair acc.', 'furniture accessories'),
('charbroilers', 'cooking equipment'),
('check presenters', 'tabletop display & decor'),
('cheese shakers', 'tabletop accessories'),
('cheese slicers & cutters', 'kitchen supplies'),
('chef apparels', 'apparel & textile'),
('chef bases', 'refrigeration equipment'),
('chef knives', 'kitchen cutlery'),
('china - bowls', 'dinnerware - china'),
('china - cups', 'dinnerware - china'),
('china - dinnerware acc.', 'dinnerware - china'),
('china - dishes', 'dinnerware - china'),
('china - plates', 'dinnerware - china'),
('china - platters', 'dinnerware - china'),
('china - spoons', 'dinnerware - china'),
('chopstick holders', 'tabletop accessories'),
('chopsticks', 'silverware & flatware'),
('chrome wire shelves', 'shelving'),
('cimeter knives', 'kitchen cutlery'),
('clam & oyster knives', 'kitchen cutlery'),
('clay pots', 'asian cookware'),
('cleaning brushes and scrapers', 'cleaning supplies'),
('cleaning supply organizers', 'cleaning supplies'),
('clothes pins & pegs', 'kitchen supplies'),
('cocktail glasses', 'beverageware - glass'),
('cocktail shakers & strainers', 'bar supplies'),
('coffee & tea brewers & warmers', 'beverage equipments'),
('coffee & tea servers', 'beverageware'),
('coffee airpots & stands', 'coffee service'),
('coffee decanters', 'coffee service'),
('coffee filters', 'd -drink supplies'),
('coffee presses', 'coffee service'),
('coffee service acc.', 'coffee service'),
('coffee sleves', 'd -drink supplies'),
('coffee stirrers', 'd -drink supplies'),
('coffee urns', 'beverage equipments'),
('colanders', 'kitchen supplies'),
('cold food tables', 'refrigeration equipment'),
('commercial griddles', 'cooking equipment'),
('commercial mixer', 'food prep equipment'),
('commercial slicers', 'food prep equipment'),
('commerical trash cans', 'trash containers & receptacles'),
('compartment sinks', 'warewashing equipment'),
('compliance signs', 'signs & crowd control'),
('compostable hinged containers', 'd -take out containers'),
('condiment holders & shakers', 'tabletop accessories'),
('condiment organizers & racks', 'tabletop accessories'),
('condiment pump dispensers', 'kitchen supplies'),
('convection ovens', 'cooking equipment'),
('cooking chopsticks', 'asian cooking utensil'),
('cooking equipment a&p', 'cooking equipment'),
('cooking scoops', 'asian cooking utensil'),
('cookware acc.', 'cookware'),
('corers, peelers & dividers', 'kitchen supplies'),
('corkscrews', 'bar supplies'),
('countertop convection ovens', 'cooking equipment'),
('countertop food warmers', 'food holding and warming equipment'),
('countertop griddles', 'cooking equipment'),
('creamers', 'beverageware'),
('crepe & waffle makers', 'cooking equipment'),
('crinkle knives', 'kitchen cutlery'),
('crocks', 'food storage'),
('crowd control', 'signs & crowd control'),
('cup & lid organizers', 'cups, lids & straws dispensers & organizers'),
('cup carriers', 'd -drink supplies'),
('cup dispensers', 'cups, lids & straws dispensers & organizers'),
('cups', 'beverageware'),
('curtains', 'apparel & textile'),
('cushions and seats', 'seating'),
('custom art fee', 'fees'),
('cut resistant gloves', 'kitchen supplies'),
('cutlery bins', 'kitchen supplies'),
('cutting board acc.', 'kitchen supplies'),
('cutting boards', 'kitchen supplies'),
('d-aprons', 'd -apparels'),
('d-culteries', 'd -tabletops'),
('d-facemasks', 'd -apparels'),
('d-gloves', 'd -apparels'),
('d-hats and hairnets', 'd -apparels'),
('d-picks & skewers', 'd -food prep & wraps'),
('deck faucets', 'warewashing equipment'),
('deep fryers', 'cooking equipment'),
('degreasers', 'cleaners'),
('deli cases', 'refrigeration equipment'),
('dessert dishes', 'dinnerware - others'),
('dessert glasses', 'beverageware - glass'),
('dim sum carts', 'racks & carts'),
('dim sum oil papers', 'd -food prep & wraps'),
('diposable chopsticks', 'd -tabletops'),
('dipper well sinks', 'warewashing equipment'),
('dipping cabinets', 'refrigeration equipment'),
('dishtables', 'warewashing equipment'),
('dishwashers', 'warewashing equipment'),
('display domes, trays & covers', 'bakery supplies'),
('doily papers', 'd -tabletops'),
('dough boxes and pans', 'pizza supplies'),
('dough cutters', 'bakery supplies'),
('dough sheeters', 'food prep equipment'),
('doughnut baskets', 'bakery supplies'),
('drainer cleaners', 'cleaners'),
('draining grates', 'kitchen supplies'),
('dry goods', 'consumables'),
('dumping fee', 'fees'),
('dunnage racks', 'racks & carts'),
('egg rings', 'kitchen supplies'),
('electric fryers', 'cooking equipment'),
('electric hot plates', 'cooking equipment'),
('electric skillets', 'small appliances'),
('electric steamers', 'cooking equipment'),
('entrance mats', 'floor mats'),
('epoxy wire shelves', 'shelving'),
('equipment stands', 'work tables & equipment stands'),
('fast food trays', 'trays'),
('filter papers', 'cleaning supplies'),
('flashlights', 'safety supplies'),
('flatware holders', 'tabletop accessories'),
('floor drain strainers', 'cleaning supplies'),
('flour sieves & swifters', 'bakery supplies'),
('foam hinged containers', 'd -take out containers'),
('foam plates', 'd -dinnerwares'),
('foam soup cups', 'd -take out containers'),
('foam trays', 'd -take out containers'),
('foil food pans & containers', 'd -take out containers'),
('folding tables', 'tables'),
('food chillers', 'kitchen supplies'),
('food dippers & dishers', 'kitchen supplies'),
('food mills', 'kitchen supplies'),
('food portioner', 'serving utensil'),
('food prep brushes', 'kitchen supplies'),
('food prep equipment a&p', 'food prep equipment'),
('food prep tables', 'refrigeration equipment'),
('food processors', 'food prep equipment'),
('food serving baskets', 'kitchen supplies'),
('food storage boxes', 'food storage'),
('food storage containers', 'food storage'),
('food torches', 'kitchen supplies'),
('food transporters', 'catering supplies'),
('forks', 'silverware & flatware'),
('freezers', 'refrigeration equipment'),
('french fry cutters', 'kitchen supplies'),
('fruit & vegetable cutters', 'food prep equipment'),
('fry baskets', 'kitchen supplies'),
('fry pans', 'cookware'),
('fryer pots', 'cookware'),
('fuel surcharges', 'fees'),
('funnels', 'kitchen supplies'),
('garlic presses', 'kitchen supplies'),
('glass - bowls', 'dinnerware - glass'),
('glass - plates', 'dinnerware - glass'),
('glass coffee mugs', 'beverageware - glass'),
('glass hangers', 'bar supplies'),
('glass pie plates', 'dinnerware - serving and display ware'),
('glove holders', 'janitorial dispensers'),
('graters', 'kitchen supplies'),
('gravy and sauce boats', 'tabletop accessories'),
('grease traps', 'plumbing'),
('griddle screens & holders', 'cleaning supplies'),
('griddles', 'cookware'),
('grill & basting covers', 'kitchen supplies'),
('grill screens & holders', 'cleaning supplies'),
('guest checks & invoice books', 'd -office supplies'),
('hamburger presses', 'kitchen supplies'),
('hand sanitizer dispensers', 'janitorial dispensers'),
('hand sinks', 'warewashing equipment'),
('hand soaps', 'cleaners'),
('heat lamps', 'food holding and warming equipment'),
('heavy duty aprons', 'safety supplies'),
('heavy duty gloves', 'safety supplies'),
('high chairs and boosters', 'seating'),
('holding / proofing cabinets', 'food holding and warming equipment'),
('hood filters', 'cleaning supplies'),
('hooks & pins', 'asian cooking utensil'),
('hostess & teller signs', 'signs & crowd control'),
('hot food tables', 'food holding and warming equipment'),
('hot plates', 'cooking equipment'),
('ice bins', 'ice machines'),
('ice buckets', 'bar supplies'),
('ice cream cone holders', 'kitchen supplies'),
('ice machine a&p', 'ice machines'),
('ice makers', 'ice machines'),
('ice picks', 'bar supplies'),
('ice shavers', 'small appliances'),
('ice-cream dishers & scoops', 'kitchen supplies'),
('induction cookers & ranges', 'cooking equipment'),
('ingredient bins', 'food storage'),
('insect traps', 'pest control'),
('inset pans', 'food storage'),
('insulated beverage dispensers', 'catering supplies'),
('jiggers', 'bar supplies'),
('jugs, buckets & pails', 'cleaning supplies'),
('juice extractors', 'kitchen supplies'),
('juicers', 'beverage equipments'),
('kitchen scoops & holders', 'kitchen supplies'),
('kitchen shears', 'kitchen cutlery'),
('knife bags, rolls & cases', 'kitchen cutlery'),
('knife holders & racks', 'kitchen cutlery'),
('knife sharpeners', 'kitchen cutlery'),
('knives', 'silverware & flatware'),
('labels', 'office supplies'),
('ladles', 'kitchen utensils'),
('laundry cleaners', 'cleaners'),
('lazy susans', 'tables'),
('led signs', 'signs & crowd control'),
('lid dispensers', 'cups, lids & straws dispensers & organizers'),
('lighters', 'catering supplies'),
('lime squeezers', 'bar supplies'),
('liquor pourers & savers', 'bar supplies'),
('loaf pans', 'bakery supplies'),
('lockers', 'shelving'),
('lugs & tote boxes', 'bussing & warewashing'),
('madoline slicers', 'food prep equipment'),
('malt cups', 'bar supplies'),
('measuring cups', 'bakery supplies'),
('measuring cups & spoons', 'kitchen supplies'),
('meat and bone saws', 'food prep equipment'),
('meat choppers & grinders', 'food prep equipment'),
('meat tenderizers', 'kitchen supplies'),
('medicine cases', 'safety supplies'),
('melamine - asianwares', 'dinnerware - melamine'),
('melamine - bowls', 'dinnerware - melamine'),
('melamine - cups', 'dinnerware - melamine'),
('melamine - dishes', 'dinnerware - melamine'),
('melamine - plates', 'dinnerware - melamine'),
('melamine - platters', 'dinnerware - melamine'),
('melamine - spoons', 'dinnerware - melamine'),
('menu covers', 'tabletop display & decor'),
('menu stands & holders', 'tabletop display & decor'),
('merchandising refrigerators', 'refrigeration equipment'),
('metal frame chairs', 'seating'),
('metal skewers', 'kitchen supplies'),
('microwaves', 'small appliances'),
('mitts and gloves', 'apparel & textile'),
('mixing bowls', 'kitchen supplies'),
('molds', 'bakery supplies'),
('mop buckets and wringers', 'cleaning supplies'),
('mop sinks', 'warewashing equipment'),
('mops & acc.', 'cleaning supplies'),
('muddlers & bar spoons', 'bar supplies'),
('muffin pans', 'bakery supplies'),
('napkin dispensers', 'tabletop accessories'),
('napkins', 'd -tabletops'),
('neon markers', 'office supplies'),
('non-skid trays', 'trays'),
('norens', 'decorations'),
('oil & vinegar cruets & racks', 'tabletop accessories'),
('oil filters & acc.', 'kitchen supplies'),
('other racks & carts', 'racks & carts'),
('other shelves', 'shelving'),
('outdoor chairs', 'seating'),
('outdoor tables', 'tables'),
('oven & grill cleaners', 'cleaners'),
('oven to table', 'dinnerware - serving and display ware'),
('oven to table items', 'dinnerware - serving and display ware'),
('overflow pipes', 'bar supplies'),
('packing tape', 'office supplies'),
('paddles', 'kitchen utensils'),
('pail openers', 'kitchen supplies'),
('pairing knives', 'kitchen cutlery'),
('pallet wrap', 'forest supplies'),
('pallets', 'forest supplies'),
('pan & can racks', 'racks & carts'),
('panini grills', 'cooking equipment'),
('paper bowls', 'd -dinnerwares'),
('paper box containers', 'd -take out containers'),
('paper cold cups', 'd -drinkwares'),
('paper food pails', 'd -take out containers'),
('paper food wraps & liners', 'd -food prep & wraps'),
('paper grocery & deli bags', 'd -bags'),
('paper hinged containers', 'd -take out containers'),
('paper hot cups', 'd -drinkwares'),
('paper plates', 'd -dinnerwares'),
('paper portion cups', 'd -take out containers'),
('paper soup cups', 'd -take out containers'),
('paper towel dispensers', 'janitorial dispensers'),
('paper towels', 'd -janitorial'),
('paper trays', 'd -take out containers'),
('pasta and noodle machines', 'food prep equipment'),
('pasta cookers', 'cooking equipment'),
('pasta cookers & steamers', 'cookware'),
('pastry & cookie cutters', 'bakery supplies'),
('pastry bags', 'bakery supplies'),
('pastry brushes', 'bakery supplies'),
('pastry tubes & nails', 'bakery supplies'),
('pie pans', 'bakery supplies'),
('pie servers', 'bakery supplies'),
('pie/cake cutters & markers', 'bakery supplies'),
('pitchers', 'beverageware'),
('pizza bags', 'pizza supplies'),
('pizza baking stones', 'pizza supplies'),
('pizza cutters', 'pizza supplies'),
('pizza delivery bags', 'pizza supplies'),
('pizza dough dockers', 'pizza supplies'),
('pizza oven brushes', 'pizza supplies'),
('pizza peels', 'pizza supplies'),
('pizza screens', 'pizza supplies'),
('pizza servers', 'pizza supplies'),
('pizza trays & pans', 'pizza supplies'),
('placemats', 'd -tabletops'),
('plastic 2-p containers', 'd -take out containers'),
('plastic clear & produce bags', 'd -bags'),
('plastic clear 2-p containers', 'd -take out containers'),
('plastic clear hinged container', 'd -take out containers'),
('plastic cold cups', 'd -drinkwares'),
('plastic fish baskets', 'kitchen supplies'),
('plastic food pans', 'food storage'),
('plastic food wraps', 'd -food prep & wraps'),
('plastic hinged containers', 'd -take out containers'),
('plastic micro-safe containers', 'd -take out containers'),
('plastic plates', 'd -dinnerwares'),
('plastic platters', 'd -dinnerwares'),
('plastic portion cups', 'd -take out containers'),
('plastic pourers', 'bar supplies'),
('plastic soup cups', 'd -take out containers'),
('plastic t-shirt bags', 'd -bags'),
('plastic take out bowls', 'd -take out containers'),
('plastic trays', 'd -take out containers'),
('plate covers', 'dinnerware - others'),
('plates', 'dinnerware - others'),
('plumbing a&p', 'plumbing'),
('podiums', 'other furnitures'),
('poles & handles', 'cleaning supplies'),
('poly cutting boards', 'food prep equipment'),
('portable cooking equipment', 'catering supplies'),
('pot & carving forks', 'kitchen cutlery'),
('pot holders', 'apparel & textile'),
('potato mashers', 'kitchen supplies'),
('potato risers', 'kitchen supplies'),
('pre-rinse faucets & sprayers', 'warewashing equipment'),
('prep sinks', 'warewashing equipment'),
('price guns', 'office supplies'),
('pump kits', 'bar supplies'),
('rack & cart a&p', 'racks & carts'),
('ramekins & sauce cups', 'tabletop accessories'),
('receipt papers & paper rolls', 'd -office supplies'),
('refrigerated display cases', 'refrigeration equipment'),
('refrigeration equipment a&p', 'refrigeration equipment'),
('refrigerators', 'refrigeration equipment'),
('restaurant ranges', 'cooking equipment'),
('restaurant ticket holders', 'kitchen supplies'),
('rice containers', 'asianware'),
('rice cookers & warmers', 'small appliances'),
('rice grinders', 'small appliances'),
('rice mixing bowls', 'asianware'),
('rice nets', 'asianware'),
('rice prep containers', 'asian cookware'),
('rice scoops', 'asianware'),
('rolling pins', 'bakery supplies'),
('rubber mats', 'floor mats'),
('safes', 'office supplies'),
('safety signs', 'signs & crowd control'),
('sake bottles & cups', 'beverageware'),
('sake warmers', 'beverage equipments'),
('salad bowls', 'dinnerware - serving and display ware'),
('salad dryers & spinners', 'food prep equipment'),
('salamander broilers', 'cooking equipment'),
('salt & pepper refillers', 'kitchen supplies'),
('salt & pepper shakers & mills', 'tabletop accessories'),
('sandwich spreaders', 'kitchen cutlery'),
('sandwich stations', 'food holding and warming equipment'),
('sauce pans', 'cookware'),
('sauce pots', 'cookware'),
('saute pans', 'cookware'),
('scales', 'kitchen supplies'),
('scrapers', 'kitchen utensils'),
('screens', 'other furnitures'),
('seafood prep tools', 'kitchen supplies'),
('seafood utensils', 'silverware & flatware'),
('sealing machines', 'food prep equipment'),
('serving spoons, forks & knives', 'serving utensil'),
('serving wares', 'd -tabletops'),
('shelf liners', 'bar supplies'),
('shelving a&p', 'shelving'),
('shopping baskets', 'kitchen supplies'),
('sign frame', 'signs & crowd control'),
('sink drains & strainers', 'plumbing'),
('sink nozzles & spouts', 'warewashing equipment'),
('skimmers', 'kitchen utensils'),
('slicers', 'kitchen supplies'),
('slicing knives', 'kitchen cutlery'),
('small appliances a&p', 'small appliances'),
('sneeze guards', 'food holding and warming equipment'),
('soap dispensers', 'janitorial dispensers'),
('soda, tea, & water glasses', 'beverageware - glass'),
('soy sauce bottles', 'tabletop accessories'),
('spatulas', 'kitchen utensils'),
('special items', 'internal use'),
('speed rails', 'bar supplies'),
('spice grinders', 'food prep equipment'),
('splash guards', 'warewashing equipment'),
('sponges, scrubs, & scour pads', 'cleaning supplies'),
('spoodles', 'kitchen utensils'),
('spoons', 'silverware & flatware'),
('spray bottles', 'cleaning supplies'),
('squeegees & acc.', 'cleaning supplies'),
('squeeze bottles', 'kitchen supplies'),
('stacking chairs', 'seating'),
('steak knives', 'kitchen cutlery'),
('steak weights', 'kitchen supplies'),
('steam table food pans', 'food storage'),
('steam table pan adapter bars', 'food storage'),
('steamers', 'asian cookware'),
('stirrer dispensers', 'cups, lids & straws dispensers & organizers'),
('stock pot ranges', 'cooking equipment'),
('stock pots', 'cookware'),
('storage jars & canisters', 'food storage'),
('strainers', 'kitchen utensils'),
('straw dispensers', 'cups, lids & straws dispensers & organizers'),
('straws', 'd -drink supplies'),
('sugar shakers & pourers', 'tabletop accessories'),
('sushi cases', 'refrigeration equipment'),
('sushi containers', 'd -take out containers'),
('sushi molds & mats', 'asianware'),
('sushi servewares', 'asianware'),
('syrup dispensers', 'tabletop accessories'),
('table acc.', 'furniture accessories'),
('table bases', 'tables'),
('table mounted shelves', 'shelving'),
('table tops', 'tables'),
('tabletop baskets & containers', 'tabletop accessories'),
('tabletop signs & holders', 'tabletop display & decor'),
('tea bag chests', 'tabletop accessories'),
('tea bags', 'd -drink supplies'),
('tea ball infusers', 'coffee service'),
('tea pots', 'beverageware'),
('test stipes', 'cleaners'),
('thermal cookers', 'small appliances'),
('thermometers', 'kitchen supplies'),
('timers & clocks', 'kitchen supplies'),
('tip trays', 'tabletop display & decor'),
('toasters', 'small appliances'),
('toilet paper dispensers', 'janitorial dispensers'),
('toilet plungers', 'restroom supplies'),
('toilet seat cover dispensers', 'janitorial dispensers'),
('toilet seat covers', 'd -janitorial'),
('toilet tissues', 'd -janitorial'),
('tongs', 'serving utensil'),
('toothpick dispensers', 'tabletop accessories'),
('tortilla servers & taco holder', 'tabletop accessories'),
('trash can dollies', 'trash containers & receptacles'),
('trash can liners', 'd -janitorial'),
('trash pickup and reaching tool', 'cleaning supplies'),
('tray fits', 'bakery supplies'),
('tray stands', 'trays'),
('tumblers', 'beverageware'),
('turners', 'kitchen cutlery'),
('urinal deodorizers', 'restroom supplies'),
('utility knives', 'kitchen cutlery'),
('waiting benches', 'seating'),
('walk-in refrigeration', 'refrigeration equipment'),
('wall mount faucets', 'warewashing equipment'),
('wall mount shelves', 'shelving'),
('warewash cleaners', 'cleaners'),
('warewashing equipment a&p', 'warewashing equipment'),
('warewashings racks & acc.', 'bussing & warewashing'),
('wastebaskets & trash cabinets', 'trash containers & receptacles'),
('water boilers', 'beverage equipments'),
('wet towels', 'd -tabletops'),
('whip cream dispensers', 'beverage equipments'),
('whips', 'kitchen utensils'),
('window & multisurface cleaners', 'cleaners'),
('wine buckets & stands', 'bar supplies'),
('wine glasses', 'beverageware - glass'),
('wok ranges', 'cooking equipment'),
('woks & acc.', 'asian cookware'),
('wood frame chairs', 'seating'),
('wooden spoons', 'kitchen utensils'),
('work tables', 'work tables & equipment stands'),
('work tables & equipment stand', 'work tables & equipment stands'),
('work tables/equipment stand a&', 'work tables & equipment stands'),
('write on boards', 'signs & crowd control'),

)

ITEM_D_DEPT = dict(ITEM_L_DEPT)


ITEM_D_CATE = {}
for k,v in ITEM_L_DEPT: ITEM_D_CATE.setdefault(v, []).append(k)
ITEM_L_CATE = ITEM_D_CATE.items()
ITEM_L_CATE.sort(key=lambda f_v: f_v[0])

"""
ZONES = (
    ('*Other*', set([]), ),
    ('Downtown', set([ 0, 2 , 4]), ),
    ('Chinatown', set([ 0, 2, 4 ]), ),
    ('Fisherman', set([ 0, 2, 4 ]), ),
    ('GoldenGate', set([ 0, 2, 4 ]), ),
    ('Sunset', set([ 0, 2, 4 ]), ),
    ('Richmond', set([ 0, 2, 4 ]), ),
    ('Mission', set([ 0, 2, 4 ]), ),
    
    ('Eastbay', set([ 1, 3]), ),
    ('Southbay', set([ 1, 3]), ),
    ('Peninsula', set([ 1, 3]), ),
    
    ('NorthBay', set([ 1, 4]), ),    
)
"""

ZONES = (
    ('*Other*', set([]), None),
    ('SF East', set([ 0, 2 , 4]), 'Downtown, Chinatown, Fisherman'),
    ('SF West', set([ 0, 2, 4 ]), 'GoldenGate, Richmond, Sunset'),
    ('Mission', set([ 0, 2, 4 ]), None),
    
    ('Eastbay', set([ 1, 3]), 'Albany,Emeryville,Berkeley,Oakland,Alameda,San Leandro'),
    ('Southbay', set([ 1, 3]), 'San Jose, Santa Clara, Palo Alto, Mountain View, Sunnyvale'),
    ('Peninsula', set([ 1, 3]), 'GlenPark, Daily City, San Bruno, San Mateo, Millbrae'),
    
    ('NorthBay', set([ 1, 4]), 'Mill Valley, San Rafael, Vallejo'),    
)


